name: TEST - Deployment to Firebase App Distribution

# TEST로 시작하는 tag가 push되면 동작
on:
  push:
    tags:
      - TEST*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Firebase
        uses: pocket-apps/action-setup-firebase@v2
        with:
          firebase-token: ${{secrets.FIREBASE_TOKEN}}

      - name: set up JDK 11
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: ADD LOCAL PROPERTIES
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build AAB
        id: buildAAB
        run: ./gradlew bundleRelease

      - name: Sign AAB
        id: signAAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload apk to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: pulja-aos-tester
          file: app/build/outputs/bundle/release/app-release.aab