apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ${ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/app-sample
    newName: ${ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/app-sample
    newTag: app_latest
