apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
- name: kustomization-eks-repository
  newName: 000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/app
  newTag: app_latest
